[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools',
]

[project]
name = "nebari_stage_hello_world"
version = "0.0.1"
dependencies = [
    "nebari"
]

[project.entry-points.nebari]
nebari-stage-hello-world = "nebari_stage_hello_world"